id: AD1383080
base_file: f8797.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:51.084454
  last_modified_at: 2022-06-17 11:28:51.084456
