id: AD1383080
base_file: f470E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:51.083322
  last_modified_at: 2022-06-17 11:28:51.083326
