id: AD1383080
base_file: f33E0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:51.081414
  last_modified_at: 2022-06-17 11:28:51.081422
